import{a as q,S as I,i as a}from"./assets/vendor-BLPZKqeQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const M="50377156-76a0d970257c0a39042cd42de",$="https://pixabay.com/api/";async function g(r,t=1){try{return(await q.get(`${$}`,{params:{key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(s){throw console.error("Error fetching images:",s),s}}const m=document.querySelector(".gallery"),p=document.querySelector(".loader-container"),y=document.querySelector(".load-more-button");let i=null;function h(r,t=!1){const s=r.map(({webformatURL:n,largeImageURL:e,tags:o,likes:l,views:S,comments:v,downloads:P})=>`
            <li class="gallery-item">
                <a href="${e}">
                    <img class="gallery-image" src="${n}" alt="${o}" loading="lazy" />
                    <div class="info">
                        <p class="info-item"><b>Likes</b> ${l}</p>
                        <p class="info-item"><b>Views</b> ${S}</p>
                        <p class="info-item"><b>Comments</b> ${v}</p>
                        <p class="info-item"><b>Downloads</b> ${P}</p>
                    </div>
                </a>
            </li>
        `).join("");t?(m.insertAdjacentHTML("beforeend",s),i&&i.refresh()):(m.innerHTML=s,i&&i.destroy(),i=new I(".gallery a",{captionsData:"alt",captionDelay:250}))}function B(){m.innerHTML="",i&&(i.destroy(),i=null)}function b(){p.classList.add("is-loading")}function c(){p.classList.remove("is-loading")}function C(){y.classList.remove("is-hidden")}function L(){y.classList.add("is-hidden")}const u=document.querySelector(".search-form"),E=u.querySelector('input[name="search-text"]'),H=document.querySelector(".load-more-button"),O=document.querySelector(".gallery");let d=1,f="";const w=15;u.addEventListener("submit",async r=>{if(r.preventDefault(),f=E.value.trim(),d=1,B(),L(),b(),!f){a.warning({title:"Warning",message:"Please, insert what are you looking for",position:"topRight"}),c(),u.reset();return}try{const t=await g(f,d);c(),t.hits.length>0?(h(t.hits),t.totalHits>w?C():a.info({message:"This is the End.",position:"bottomCenter"})):a.info({title:"Info",message:"Sorry, no suitable images. Please, try again!",position:"topRight"})}catch(t){c(),a.error({title:"Mistake",message:"Unfortunately, impossible to load images now. Please, try later.",position:"topRight"}),console.error(t)}finally{u.reset()}});H.addEventListener("click",async()=>{d+=1,b();try{const r=await g(f,d);c(),h(r.hits,!0);const t=O.querySelector(".gallery-item");if(t){const{height:n}=t.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}d*w>=r.totalHits&&(L(),a.info({message:"This is the end of search",position:"bottomCenter"}))}catch(r){c(),a.error({title:"Памылка",message:"Unfortunately, impossible to load images now. Please, try later.",position:"topRight"}),console.error(r)}});
//# sourceMappingURL=index.js.map
